# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
    extensions: ["strikethrough", "superscript", "footnote"]
gems:
  - jemoji

future: false

# Site settings
title: "THE CRUMPLED LOGARITHM"
description: > # this means to ignore newlines until "email:"
  A Personal Blog

email: hi@uxjulia.com
#blog logo
logo: "/assets/images/jn_logo.png"
# blog cover
cover: "/assets/images/bg.jpg"

#images for use on the "currently" page
book: "/assets/images/books/book1.jpg"
game: "/assets/images/games/game1.png"

name: 'Julia Nguyen'
author: 'Julia N.'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.uxjulia.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/uxjulia
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/uxjulia
    desc: Connect with me LinkedIn
    share_url:
    share_title:
    share_link:

#  - icon:	github
#    url:	https://github.com/uxjulia
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# default settings
defaults:
   -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"

exlude: [ "gemfile", "gemfile.lock", "Rakefile", "publish.*" ]
