 # Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
source: /Users/Home/Dropbox/Jekyll/uxjulia
title: "THE CRUMPLED LOGARITHM"
description: > # this means to ignore newlines until "email:"
   Personal ramblings about technology, gadgets and experience design.

email: hi@uxjulia.com
#blog logo
logo: "/assets/images/jn_logo.png"
# blog cover
cover: "/assets/images/bg.jpg"

name: 'Julia Nguyen'
author: 'Julia Nguyen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.uxjulia.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/uxjulia
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/uxjulia
    desc: Connect with me LinkedIn
    share_url:
    share_title:
    share_link:

#  - icon:	github
#    url:	https://github.com/uxjulia
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# default settings
defaults:
    scope:
       path: ""
       type: "posts"
    values:
       layout: "post"
