# Site settings
title: The Grassy Median
email: hi@uxjulia.com
description: "A personal blog about technology, gadgets and user experience"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.uxjulia.com" # the base hostname & protocol for your site
twitter_username: uxjulia
github_username:  uxjulia

# Build settings
markdown: kramdown
